apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
spec:
  selector:
  matchLabels:
    app: redis
  replicas: 2
  template:
    metadata:
      labels:
        app: redis
        tipo: cache
        time: infra
    spec:
      containers:
        - name: redis
          image: nginx:1.16.1
          ports:
          - containerPort: 80