name: "Create cluster using KinD"
on:
  push:
    branches: [ main ]

jobs:
  kind:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: engineerd/setup-kind@v0.5.0
        with:
          version: "v0.9.0"
      - name: Testing
        run: |
          kubectl cluster-info
          kubectl get pods -n kube-system
          echo "current-context:" $(kubectl config current-context)
          echo "environment-kubeconfig:" ${KUBECONFIG}
      - name: Creating
        env:
          EXERCICIOSK8S: Kubernetes/exercicios/*.yml
        run: |
          for exercicio in $EXERCICIOSK8S; do echo "-_-_-_-_-_-_-_-" ; \
          echo " " ; \
          echo "RODANDO EXERCÍCIO $exercicio" ; \
          echo " " ; \
          kubectl create -f $exercicio ; sleep 5s ; echo " " ; done
          echo " " ; \
          sleep 25s ; \
          echo "ESTADO GERAL DO CLUSTER:" ; \
          echo " " ; \
          kubectl get all
